.travis.yml, src/auto/number.js, src/auto/util.js, test/unit/auto/util-spec.js, test/unit/number-spec.js
修复如下scale计算的时候，会陷入死循环的问题
```
const scale = Scale.linear({
min: 0.999999999999997,
max: 1.000000000000033,
tickCount: 5
});
```
=> fix: 修复计算精度有问题的scale，陷入死循环的问题

src/category/base.ts, tests/unit/category-spec.ts, tests/unit/time-cat-spec.ts
关联：https://github.com/antvis/G2/issues/2138
G2 在 dodge 后，x 会超出 scale 范围，导致图表绘制出错。
=> fix: category scale 在做 scale 时，对超出范围的数据不返还 NaN

src/util/extended.ts, tests/bugs/issue-1-spec.js, tests/bugs/issue-1-spec.ts, tests/bugs/issue-62-spec.ts
=> fix(extentded): fix oom when min, max is invalid

src/util/extended.ts, tests/unit/tick-method/cat-spec.ts
Tick count 0 导致 extended 跳不出 while 循环。
=> fix: 修复 tickCount 0 导致的 oom

package.json, src/category/base.ts, tests/unit/category-spec.ts
使用 index map 提升 indexOf 的在大数据下的性能。为 G2 在大数据渲染上提升 800% 性能。
=> perf: build index map for scale.tranlate

__tests__/unit/scales/base.spec.ts, __tests__/unit/scales/constant.spec.ts, __tests__/unit/scales/identity.spec.ts, __tests__/unit/tick-methods/baisc.spec.ts, src/scales/base.ts, src/scales/constant.ts, src/scales/identity.ts, src/types.ts
之前忽略了有的比例尺没有 getTicks 方法，比如 category，band 这些。所以 BaseOptions 里面也包含了 tickCount 这些属性，并且基类有 getTicks 方法。因为社区小伙伴要先从 category 入手，为了防止迷糊，做了以下简单的重构。
- 将 BaseOptions 里面的和 getTicks 相关的选项抽离出来为 TickOptions，有 getTicks 的比例尺的类型 & 上这个类型。
- 移除了 Base 里面的 getTicks 方法，需要 getTicks 的子类自己实现该方法即可。
=> refactor(type): extract TickOptions from BaseOptions

.eslintrc.js, __tests__/unit/scales/base.spec.ts, src/scales/base.ts, src/scales/category.ts, src/scales/constant.ts, src/scales/identity.ts
发现现在覆盖默认配置的方式不能多层继承，所以修改了一下 Base 类覆盖默认配置的方式。修改之后的覆盖方式如下：
```ts
type CategoryOptions = {};
class Category<O extends CategoryOptions> extends Base<O> {
protected getOverrideDefaultOptions() {
return {/*...*/}  as O;
}
public clone() {
return new Category<O>(this.options);
}
}
type BandOptions = {};
class Band extends Category<BandOptions> {
protected getOverrideDefaultOptions() {
return {/*...*/} ;
}
}
```
=> refactor(base): add getDefaultOptions to override defualt options

__tests__/bugs/issue-53.spec.ts, __tests__/unit/scales/linear.spec.ts, __tests__/unit/tick-methods/linear.spec.ts, __tests__/unit/utils/wilkinson-extended.spec.ts, src/utils/wilkinson-extended.ts
修复旧版本的 wilkinsonExtended 的实现有 bug（linear 使用）在小数值下，无法实现均匀分配的 bug
=> fix: fix the bug that the array spacing is not the same

__tests__/unit/scales/band.spec.ts, __tests__/unit/scales/pow.spec.ts
=> fix: fix wrong usage for toBeCloseTo() API

__tests__/unit/scales/base.spec.ts, __tests__/unit/scales/continuous.spec.ts, src/scales/band.ts, src/scales/base.ts, src/scales/constant.ts, src/scales/continuous.ts, src/scales/identity.ts, src/scales/linear.ts, src/scales/log.ts, src/scales/ordinal.ts, src/scales/point.ts, src/scales/pow.ts, src/scales/quantile.ts, src/scales/quantize.ts, src/scales/sqrt.ts, src/scales/threshold.ts, src/types.ts
重构了一下代码，抽取了一些复用逻辑，主要的修改如下：
- 梳理了所有 scale 的使用流程：初始化和更新 options 的时候，根据传入的 options 和已有的 options 更新内部状态 rescale，然后根据内部的状态去 map 和 invert。
- 将 getOverrideDefaultOptions 变成了 getDefaultOptions，每个比例尺在 getDefaultOptions 返回完整的默认值，这样可读性更强。
- continuous 类的比例尺
- nice 和 getTicks 都提取到 continuous 比例尺中。
- chooseTransform 和 chooseUnTransform 的合并。
=> refactor: unify scale flow and simplify code

__tests__/unit/tick-methods/wilkinson-extended.spec.ts, __tests__/unit/utils/add.spec.ts, src/tick-methods/wilkinson-extended.ts, src/utils/precision-add.ts
之前的 fix 虽然解决了间隔大小不一致的问题，但是对更小的小数值会出错（例如0.0001），原因是处理浮点数计算问题的算法不够严谨，在这里做出修正。
=> fix: fix extended-algorithm accuracy problem

src/util/extended.ts, src/util/math.ts, tests/bugs/issue-3413-spec.ts, tests/unit/util/extended-spec.ts, tslint.json
fix https://github.com/antvis/G2/issues/3413
=> fix(extended): fix extended algorithm Infinite loop for NaN

.github/workflows/build.yml
昨天修 bug 的时候发现旧版 scale 的 ci 很快，原来是用了缓存。
刚刚发现 github action 也支持这个功能，遂添加上，以免去重复的 npm install 并快速得到 ci 结果。
=> ci(action): add deps cache support based on package.json 

src/util/extended.ts, src/util/pretty.ts, tests/unit/linear-spec.ts, tests/unit/util/extended-spec.ts, tests/unit/util/pretty-spec.ts
修复了下面出现死循环的问题：
```js
extended(9.899999999999999, 9.9)
pretty(9.899999999999999, 9.9)
```
出现原因是精度问题：
```js
const start = 9.899999999999999;
const end = 9.9;
const step = 5e-15;
for(let i = start; i < end; i += step) {} // 死循环 i += step 始终等于 9.899999999999999
```
```js
const start = 19799999999999996;
const end = 19799999999999996;
const step = 1;
for(let i = start; i <= end; i += step) {} // 死循环 i += step 始终等于 19799999999999996
```
解决办法
```js
const start = 9.899999999999999;
const end = 9.9;
const step = 5e-15;
const count = Math.floor((start - end) / step);
for(let i = 0; i < count; i += 1) {}
```
=> fix(ticks): tiny number for tickMethods

__tests__/unit/tick-methods/r-pretty.spec.ts, __tests__/unit/tick-methods/wilkinson-extended.spec.ts, __tests__/unit/utils/pretty-number.spec.ts, src/tick-methods/r-pretty.ts, src/tick-methods/wilkinson-extended.ts, src/utils/pretty-number.ts
修复了下面出现死循环的问题：
```js
extended(9.899999999999999, 9.9)
pretty(9.899999999999999, 9.9)
```
出现原因是精度问题：
```js
const start = 9.899999999999999;
const end = 9.9;
const step = 5e-15;
for(let i = start; i < end; i += step) {} // 死循环 i += step 始终等于 9.899999999999999
```
```js
const start = 19799999999999996;
const end = 19799999999999996;
const step = 1;
for(let i = start; i <= end; i += step) {} // 死循环 i += step 始终等于 19799999999999996
```
解决办法
```js
const start = 9.899999999999999;
const end = 9.9;
const step = 5e-15;
const count = Math.floor((start - end) / step);
for(let i = 0; i < count; i += 1) {}
```
=> fix(ticks): tickMethods for tiny numbers

src/util/extended.ts, src/util/pretty.ts, tests/unit/util/extended-spec.ts, tests/unit/util/pretty-spec.ts
处理 tickCount 为小数和负数的情况，处理办法如下
```js
const n = m < 0 ? 0 : Math.round(m);
if (n === 0) return [];
```
=> fix(ticks): handle decimal and negative tick count

__tests__/unit/tick-methods/d3-ticks.spec.ts, __tests__/unit/tick-methods/r-pretty.spec.ts, __tests__/unit/tick-methods/wilkinson-extended.spec.ts, src/tick-methods/r-pretty.ts, src/tick-methods/wilkinson-extended.ts
处理 tickCount 为小数和负数的情况，处理办法如下
```js
const n = m < 0 ? 0 : Math.round(m);
if (n === 0) return [];
```
=> fix(ticks): handle decimal and negative tickCount

src/util/extended.ts, src/util/pretty-number.ts, src/util/pretty.ts, tests/unit/util/extended-spec.ts, tests/unit/util/pretty-number-spec.ts, tests/unit/util/pretty-spec.ts
修复当 tick 的 range 是负数时候的情况。
```js
// before fix
extended(-0.4, 0) // [-0.4, -0.30000000000000004, -0.2, -0.09999999999999998, 0]
// after fix
extended(-0.4, 0) // [-0.4, -0.3, -0.2, -0.1, 0]
```
=> fix(ticks): pretty negative number

__tests__/unit/tick-methods/r-pretty.spec.ts, __tests__/unit/tick-methods/wilkinson-extended.spec.ts, __tests__/unit/utils/pretty-number.spec.ts, src/utils/pretty-number.ts
修复当 tick 的 range 是负数时候的情况。
```js
// before fix
extended(-0.4, 0) // [-0.4, -0.30000000000000004, -0.2, -0.09999999999999998, 0]
// after fix
extended(-0.4, 0) // [-0.4, -0.3, -0.2, -0.1, 0]
```
=> fix(ticks): pretty negative ticks

__tests__/unit/scales/point.spec.ts, package.json, src/scales/point.ts
```js
// This result in unexpected mapping.
const scale = new Point({
paddingInner: 0.2
});
```
=> fix(point): paddingInner should always equals to 1

.eslintrc.js, __tests__/unit/scales/sequential.spec.ts, docs/api/scales/sequential.md, package.json, src/index.ts, src/scales/sequential.ts, src/types.ts
```ts
import { Sequential, SequentialOptions } from '@antv/scale';
const scale = new Sequential({
domain: [0, 10],
interpolator: (t) => 1 - t,
});
scale.map(0.5); // 0.5
scale.map(0.2); // 0.8
scale.map(0.8); // 0.2
scale.getOptions().range; // [1, 0]
```
=> feat: add sequential scale (close #188)

.eslintrc.js, __tests__/unit/scales/diverging.spec.ts, __tests__/unit/scales/sequential.spec.ts, docs/api/scales/diverging.md, package.json, src/index.ts, src/scales/continuous.ts, src/scales/diverging.ts, src/scales/linear.ts, src/scales/pow.ts, src/scales/sequential.ts, src/types.ts, src/utils/index.ts, src/utils/interpolatize.ts
```ts
import { Diverging, DivergingOptions } from '@antv/scale';
const scale = new Diverging({
domain: [-10, 0, 10],
interpolator: (t) => 1 - t,
});
scale.map(5); // 0.25
scale.map(2); // 0.4
scale.map(-5); // 0.75
scale.getOptions().range; // [1, 0.5, 0]
```
=> feat: add diverging scale (close: #190)

.eslintrc.js, __tests__/unit/scales/band.spec.ts, __tests__/unit/utils/interMap.spec.ts, src/scales/band.ts, src/utils/index.ts, src/utils/internMap.ts
1. Optmize computeBandState: band scales only do simple calculation if no flex option.
2. Use InternMap instead of Map to deal with the key of the object type.
#193
=> feat: opt computeBandState & use internMap instead of Map

__tests__/unit/scales/band.spec.ts, __tests__/unit/scales/ordinal.spec.ts, src/scales/band.ts, src/scales/ordinal.ts, src/scales/point.ts
当 ordinal, band, point scale 比例尺显示设置了 unknown 的时候，不管该 unknown 是否是 falsy，都将不在 domain 的值映射为设置的 unknown，而不是将其添加进 indexMap。
```js
// 修复之前
const scale = new Ordinal({
domain: ['a'],
range: ['A'],
unknown: null
});
scale.map('b'); // 'A'
```
```js
// 修复之后
const scale = new Ordinal({
domain: ['a'],
range: ['A'],
unknown: null
});
scale.map('b'); // null
```
=> fix(ordinal): update map only with unset unknown

__tests__/unit/tick-methods/d3-log.spec.ts, package.json, rollup.config.js, src/tick-methods/d3-log.ts, src/utils/index.ts
背景：https://github.com/antvis/scale/issues
1. 存在误差：
```js
ticks(0.001, 1, 2);
// expect: [0.001, 0.01, 0.1, 1]
// actual: [0.01, 0.1, 1]
```
计算 tick 会对最小值和最大值求指数范围，然后基于该范围生成 tick，但是求指数的时候存在误差：
```js
Math.log(0.001) / Math.log(10); 
// expect: -3
// actual: -29999...8
```
所以实际生成的 tick 是 `[10 ^ -2, 10 ^ -1, 10 ^ 0]` 为 `[0.01, 0.001, 1]`
2. 冗余 tick
当 tickCount 大于最小值和最大值求指数范围距离之后，会在中间插入更多的 tick，导致 tick 很多。这么做的目的是让 tickCount 生效的情况，保证刻度的可读性。但是对于 log 比例尺，大部分情况应该不要用用户自己去指定 tickCount，而是按照指数递增生成。
```js
ticks(0.001, 1, 10);
// expect: [0.001, 0.01, 0.1, 1]
// actual: [0.001, 0.002, ...., 0.009, 0.1, 0.2, ....0.9, 1]
```
1. 存在误差：通过 `prettryNumber` 方法格式化数据
2. 冗余 tick：当设置 tickCount 为 -1 的时候，自动计算 tick。
```js
ticks(0.001, 1, -1); // [0.001, 0.01, 0.1, 1]
```
当 scale 发版本之后，G2 log scale 的 tickCount 默认值应该为 …
=> fix(ticks): optimize log ticks

src/tick-methods/d3-log.ts, src/utils/index.ts, src/utils/log.ts
优化计算指数的方法，之前是根据换底公式计算：会存在误差，现在使用 Math 内置的一些计算对数的方法代替：`Math.log10`，`Math.log2`。
```js
Math.log(0.001) / Math.log(10); // -2.999...8
Math.log10(0.001); // -3
```
=> refactor(ticks): calc pow more precisely

__tests__/unit/tick-methods/r-pretty.spec.ts, __tests__/unit/utils/pretty-number.spec.ts, src/utils/pretty-number.ts
#205 
修复浮点数精确度的问题
以上情况表面上是5结尾，但是 `toFixed` 的时候因为实际值更偏向 `4671` 结尾所以会舍弃掉最后一位
=> fix: fix floating point precision bug

__tests__/unit/scales/linear-breaks.spec.ts, src/scales/base.ts, src/scales/linear.ts, src/tick-methods/d3-ticks.ts, src/types.ts
```ts
const scale = new Linear({
domain: [0, 200],
breaks: [{ start: 40, end: 100, gap: 0.1 }],
});
```
增加 scale 的分段能力。配置项如下：
> todo
=> feat: add the broken function to the linear scale
