antvis/scale

- src/base.js
目前定义 defs 时：
```
chart.source(dv, {     
value: {
type: 'linear',
formatter: (val: number): string => {         
// 这里只有一个val
return `${val}`;
},
},
});
```
仅能对所有的 value 进行统一的数据格式化。
而我的场景中，是需要对不同的 value 进行不同的格式化的，目前没有找到可以配置自定义格式化的方式，所以我改了部分 g2 以及 scale 的代码，以做到：
```
chart.source(dv, {     
value: {
type: 'linear',
formatter: (val: number, key: string): string => {         
// 使用 key 识别当前是哪个 value 以自定义格式化
return customFormat(val, key);
},
},
});
```
如有不对，麻烦指出~
https://github.com/antvis/g2/pull/773
> feat(tooltip): support custom format

- src/auto/number.js
- src/linear.js
- test/unit/auto/number-spec.js
- test/unit/time-spec.js
> feat(linear): support setting minTickInterval

- src/auto/number.js
- test/bugs/issue-1-spec.js
- test/bugs/issue-7-spec.js
> fix: Fix minimum calculation error. Closed #7.

- CHANGELOG.md
- package.json
- src/auto/util.js
- test/bugs/issue-9-spec.js
> fix: fix the floating point error. Closed #9

- package.json
> feat(version): update to 0.1.3

- src/util/extended.ts
> fix: exception for only 1 tick count

- __tests__/unit/linear-spec.js
- src/base.ts
- src/linear.ts
重新加上旧版本中的minLimit/maxLimit参数：
- minLimit/maxLimit总是有效的，优先min/max
- 无效minLimit/maxLimit处理
@dxq613 再看下
> fix: add minLimit/maxLimit

- package.json
- src/base.ts
- src/linear.ts
> feat: 支持maxTickCount配置

- package.json
- src/index.ts
> feat: 将具体的scale export出来

- src/base.ts
> fix: formatter can return any

- package.json
- src/category/base.ts
- src/continuous/base.ts
- tests/unit/linear-spec.ts
> Ticks min max

- README.md
- src/continuous/quantile.ts
- src/continuous/quantize.ts
- src/index.ts
- src/tick-method/quantile.ts
- tests/unit/quantile-spec.ts
- tests/unit/quantize-spec.ts
- tests/unit/tick-method/quantile-spec.ts
* 新增两个 scale，支持分段度量 quantize，支持按照密度分布的度量 quantile
> feat(scale): add quantile, quantize scales

- package.json
- src/tick-method/linear.ts
- src/tick-method/r-prettry.ts
- src/util/interval.ts
- tests/unit/tick-method/linear-spec.ts
- tests/unit/util/interval-spec.ts
> Support interval

- package.json
> chore: v0.3.0

- CHANGELOG.md
- package.json
- src/auto/number.js
- test/unit/auto/number-spec.js
> fix: fix auto/number when min < 0 and interval is null

- src/tick-method/d3-linear.ts
- src/tick-method/index.ts
- src/util/d3-linear.ts
- tests/unit/util/d3-linear-spec.ts
> feat: support d3-linear tick method

- package.json
- src/base.ts
- src/continuous/base.ts
- src/tick-method/d3-linear.ts
- src/tick-method/linear.ts
- src/tick-method/r-prettry.ts
- src/types.ts
- src/util/strict-limit.ts
- tests/unit/linear-spec.ts
- tests/unit/util/strict-limit-spec.ts
> feat: support minLimit/maxLimit

- src/tick-method/d3-linear.ts
- src/tick-method/linear.ts
- src/tick-method/r-prettry.ts
- src/util/strict-limit.ts
简化了minLimit/maxLimit的默认设置代码，没问题就可以发个新版本了
> fix: simplify strict-limit default limit

- package.json
- src/util/d3-linear.ts
> fix: fix tslint error & run lint on CI

- package.json
- src/auto/number.js
- test/unit/auto/number-spec.js
* 负数非常小的数值会出现 ticks 计算错误的问题：https://riddle.alibaba-inc.com/riddles/f4b9e187
> fix(ticks): very little values ticks error

- src/category/time.ts
- tests/unit/time-cat-spec.ts
> fix: 修改 timeCat类型scale type

- package.json
> chore: release 0.3.2

- src/index.ts
- src/tick-method/index.ts
- tests/unit/index-spec.ts
> feat: 增加registerTickMethod扩展api

- .torch.compile.opts.js
- package.json
- src/tick-method/time-pretty.ts
- tests/unit/time-spec.ts
> fix(time): scale ticks to large cause oom

- package.json
- src/category/base.ts
- tests/unit/category-spec.ts
> fix: performance improvement by cache translate

- package.json
- src/util/extended.ts
- tests/unit/util/extended-spec.ts
> fix: 解决精度问题

- package.json
- src/base.ts
> perf: performance optimized

- README.md
> docs(readme): add Quantile and remove some scales

- __tests__/unit/scales/band.spec.ts
- __tests__/unit/scales/base.spec.ts
- __tests__/unit/scales/constant.spec.ts
- __tests__/unit/scales/continuous.spec.ts
- __tests__/unit/scales/identity.spec.ts
- __tests__/unit/scales/quantile.spec.ts
- __tests__/unit/scales/quantize.spec.ts
- __tests__/unit/scales/threshold.spec.ts
- docs/scales/band.md
- docs/scales/constant.md
- docs/scales/identity.md
- docs/scales/linear.md
- docs/scales/log.md
- docs/scales/ordinal.md
- docs/scales/point.md
- docs/scales/pow.md
- docs/scales/quantile.md
- docs/scales/quantize.md
- docs/scales/sqrt.md
- docs/scales/threshold.md
- src/scales/base.ts
- src/types.ts
> refactor: remove formatter options

- README.md
- __tests__/unit/scales/base.spec.ts
- __tests__/unit/scales/continuous.spec.ts
- __tests__/unit/scales/linear.spec.ts
- __tests__/unit/scales/ordinal.spec.ts
- __tests__/unit/scales/pow.spec.ts
- __tests__/unit/tick-methods/linear.spec.ts
- __tests__/unit/tick-methods/pretty.spec.ts
- __tests__/unit/tick-methods/wilkinson-extended.spec.ts
- src/index.ts
- src/scales/linear.ts
- src/scales/log.ts
- src/scales/pow.ts
- src/scales/sqrt.ts
- src/tick-methods/d3-linear.ts
- src/tick-methods/r-pretty.ts
- 导出了 tickMethod 和一些基本的类型。
- pretty -> rPretty
- linearTicks -> d3Linear
> refactor: remove and add exports

- __tests__/unit/utils/sequence.spec.ts
- src/tick-methods/wilkinson-extended.ts
- src/utils/sequence.ts
> perf: improve fixed-length array performance

- __tests__/unit/scales/continuous.spec.ts
- __tests__/unit/scales/log.spec.ts
- __tests__/unit/scales/quantile.spec.ts
- __tests__/unit/scales/quantize.spec.ts
- __tests__/unit/scales/time.spec.ts
- __tests__/unit/utils/d3-linear-nice.spec.ts
- src/scales/continuous.ts
- src/scales/log.ts
- src/scales/quantile.ts
- src/scales/quantize.ts
- src/scales/time.ts
- src/utils/d3-linear-nice.ts
> chore: change tick-count from 10 to 5

- package.json
> Feat scale version

- src/index.ts
> chore(index): expose useful API

- README.md
> docs: add descriptions for scales in README.md

- README.md
- __tests__/unit/tick-methods/d3-log.spec.ts
- __tests__/unit/tick-methods/wilkinson-extended.spec.ts
不知道为啥 ci 挂了，本地格式化了一下，顺便修改了 readme 的一个小问题
> docs(readme): add emoji for contribution

- src/scales/quantile.ts
- src/scales/quantize.ts
- src/scales/threshold.ts
写文章的过程中发现这个地方有更加简洁和合理的实现，简单重构了一下。
> refactor(threshold): search from thresholds instead of getDomain()

- src/scales/quantile.ts
> refactor(qunantile): remove useless code to increase test coverage

- README.en-US.md
> docs: add chinese readme

- package.json
@antv/util 2.x will be deprecated.
> chore: upgrade util to reduce size

- package.json
> fix: remove d3-scale

- tsconfig.json
Similar to https://github.com/antvis/util/pull/125
> fix: sourcemap not found
